### ISSUE TITLE
Not Currently Working on Snapchat

### ISSUE THREAD

**Issue by JeffResc** [Nepeta/Relocate#2]
Location showing as current location and not spoofed location.

**Comment by xPazz** [comment]
Works great for me, you'll need to provide more information than just "not working".

**Comment by JeffResc** [comment]
@xPazz Apologies. I’m running an iPhone 7 Plus on iOS 12.1.2 and Relocate 0.1.5. When setting the global or application-speific location, and opening SnapMap on Snapchat, my avatar is at the original/current location of the device and not the spoofed location.

**Comment by Nepeta** [comment]
@JeffResc If tweaks are disabled inside of Snapchat it won't work.

**Comment by JeffResc** [comment]
@Nepeta Ah, makes sense. Is it safe to be jailbroken and have Snapchat without having Unsub? Although I'm not running any tweaks specifically for Snapchat, I've activated Unsub on it just as a precaution.

**Comment by Nepeta** [comment]
@JeffResc I don't know, they seem to ban people.

Your best option would be to ditch Snapchat. It's a harmful, proprietary app.

**Comment by JeffResc** [comment]
Thank you for your help and suggestions, closing issue.
